inherits_from: .haml-lint_todo.yml

exclude:
- 'vendor/bundle/**/*'

linters:
  InstanceVariables:
    exclude:
      - "app/views/**/*"

  InlineStyles:
    enabled: false

  ViewLength:
    enabled: false
